#!/bin/bash

# Helper script to build the program for different OS/Architectures

GOOS=darwin GOARCH=amd64 go build -o dist/updatego-darwin_amd64 ./...
GOOS=linux GOARCH=386 go build -o dist/updatego-linux_386 ./...
GOOS=linux GOARCH=amd64 go build -o dist/updatego-linux_amd64 ./...
GOOS=linux GOARCH=arm64 go build -o dist/updatego-linux_arm64 ./...
GOOS=linux GOARCH=ppc64le go build -o dist/updatego-linux_ppc64le ./...
GOOS=linux GOARCH=s390x go build -o dist/updatego-linux_s390x ./...
GOOS=darwin GOARCH=amd64 go build -o dist/updatego-darwin_amd64 ./...
GOOS=windows GOARCH=386 go build -o dist/updatego-windows_386.exe ./...
GOOS=windows GOARCH=amd64 go build -o dist/updatego-windows_amd64.exe ./...
GOOS=freebsd GOARCH=386 go build -o dist/updatego-freebsd_386 ./...
GOOS=freebsd GOARCH=amd64 go build -o dist/updatego-freebsd_amd64 ./...
